In [56]:
##Load an image
import cv2
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from pandas import DataFrame, Series  # for convenience
import pims
import trackpy as tp
from pims import Frame
from scipy.misc import imsave
#v = pims.TiffStack('/Users/pinghanchu/Documents/Git/Data/Shot119_Cam_18333.tif')
#u = pims.TiffStack('/Users/pinghanchu/Documents/Git/Data/Shot119_Cam_18158.tif')
#v0 = tp.bandpass(v[0],1, 300,preprocess=False, percentile=0.)
#u0 = tp.bandpass(u[0],1, 300,preprocess=False, percentile=0.)
#v0 = tp.bandpass(v[0],0,300,threshold=5,truncate=4)
#u0 = tp.bandpass(u[0],0,300,threshold=5,truncate=4)

In [57]:
#plt.figure()
#plt.imshow(v0)
#plt.show()
#plt.imshow(u0)
#plt.show()

In [58]:
#imsave("/Users/pinghanchu/Documents/Git/Data/u0.png",u0)
#imsave("/Users/pinghanchu/Documents/Git/Data/v0.png",v0)

In [141]:
img1 = cv2.imread('/Users/pinghanchu/Documents/Git/Data/u0.png',0) #queryimage # left image
img2 = cv2.imread('/Users/pinghanchu/Documents/Git/Data/v0.png',0) #trainimage # right image
sift = cv2.SIFT()

# find the keypoints and descriptors with SIFT
kp1, des1 = sift.detectAndCompute(img1,None)
kp2, des2 = sift.detectAndCompute(img2,None)

FLANN_INDEX_KDTREE = 0
index_params = dict(algorithm = FLANN_INDEX_KDTREE, trees = 5)
search_params = dict(checks=50)

flann = cv2.FlannBasedMatcher(index_params,search_params)
matches = flann.knnMatch(des1,des2,k=2)

good = []
pts1 = []
pts2 = []

# ratio test as per Lowe's paper
for i,(m,n) in enumerate(matches):
    if m.distance < 0.8*n.distance:
        good.append(m)
        pts2.append(kp2[m.trainIdx].pt)
        pts1.append(kp1[m.queryIdx].pt)


In [142]:
#pts1 = np.int32(pts1)
#pts2 = np.int32(pts2)
pts1 = np.asarray(pts1)
pts2 = np.asarray(pts2)
#print(type(pts2))
F, mask = cv2.findFundamentalMat(pts1,pts2,cv2.FM_LMEDS)

# We select only inlier points
pts1 = pts1[mask.ravel()==1]
pts2 = pts2[mask.ravel()==1]


In [93]:
def drawlines(img1,img2,lines,pts1,pts2):
    ''' img1 - image on which we draw the epilines for the points in img2
        lines - corresponding epilines '''
    r,c = img1.shape
    img1 = cv2.cvtColor(img1,cv2.COLOR_GRAY2BGR)
    img2 = cv2.cvtColor(img2,cv2.COLOR_GRAY2BGR)
    for r,pt1,pt2 in zip(lines,pts1,pts2):
        color = tuple(np.random.randint(0,255,3).tolist())
        x0,y0 = map(int, [0, -r[2]/r[1] ])
        x1,y1 = map(int, [c, -(r[2]+r[0]*c)/r[1] ])
        img1 = cv2.line(img1, (x0,y0), (x1,y1), color,1)
        img1 = cv2.circle(img1,tuple(pt1),5,color,-1)
        img2 = cv2.circle(img2,tuple(pt2),5,color,-1)
    return img1,img2

In [151]:
print(pts2)
print("------------------------")
print(pts2.reshape(-1,1,2))
print("------------------------")
lines1 = cv2.computeCorrespondEpilines(pts2.reshape(-1,1,2), 2,F)
lines1 = lines1.reshape(-1,3)
img5,img6 = drawlines(img1,img2,lines1,pts1,pts2)

# Find epilines corresponding to points in left image (first image) and
# drawing its lines on right image
lines2 = cv2.computeCorrespondEpilines(pts1.reshape(-1,1,2), 1,F)
lines2 = lines2.reshape(-1,3)
img3,img4 = drawlines(img2,img1,lines2,pts2,pts1)

plt.subplot(121),plt.imshow(img5)
plt.subplot(122),plt.imshow(img3)
plt.show()

[[ 205.33088684  132.41456604]
 [ 197.64059448  149.74971008]
 [ 207.90031433  164.08091736]
 [ 148.6192627   235.37960815]
 [ 221.34857178  143.03868103]
 [ 225.93659973  153.68605042]
 [ 184.22335815  196.13186646]
 [ 184.22335815  196.13186646]]
------------------------
[[[ 205.33088684  132.41456604]]

 [[ 197.64059448  149.74971008]]

 [[ 207.90031433  164.08091736]]

 [[ 148.6192627   235.37960815]]

 [[ 221.34857178  143.03868103]]

 [[ 225.93659973  153.68605042]]

 [[ 184.22335815  196.13186646]]

 [[ 184.22335815  196.13186646]]]
------------------------


error: /Users/jenkins/miniconda/0/2.7/conda-bld/work/opencv-2.4.11/modules/calib3d/src/fundam.cpp:1135: error: (-215) npoints >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function computeCorrespondEpilines
