In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from numpy import linalg as LA
import pandas as pd
from pandas import DataFrame, Series  # for convenience
import pims
import trackpy as tp
import math
from scipy.misc import imsave
from scipy.misc import imread
shot = 119
picL = 18333
picR = 18158
bk0L = imread('./Data/Shot{}/Clean_Data_Shot{}_Cam_{}/FrameL0.tif'.format(shot,shot,picL))
bk0R = imread('./Data/Shot{}/Clean_Data_Shot{}_Cam_{}/FrameR0.tif'.format(shot,shot,picR))
height,width = bk0L.shape
print(width,height)
# Use https://automeris.io/WebPlotDigitizer/ to select ~8 corresponding points in the right and left camera
'''
calL= pd.read_csv("calL_comb.csv",header=None)
calR= pd.read_csv("calR_comb.csv",header=None)
calL.columns = ['XL','YL']
calR.columns = ['XR','YR']
calPoint = pd.concat([calL, calR], axis=1)
print(calPoint)
plt.figure(figsize=[12,12])
plt.imshow(bk0L)
plt.scatter(calPoint['XL'],calPoint['YL'], marker='o')
plt.show()
plt.figure(figsize=[12,12])
plt.imshow(bk0R)
plt.scatter(calPoint['XR'],calPoint['YR'], marker='o')
plt.show()
'''
#print(calPoint)
#'''
Pl0 = [181.544,384-211.678] # point in the left
Pr0 = [59.61,384-211.61] # point in the right
Pl1 = [223.43,384-240] 
Pr1 = [99.95,384-241.25] 
Pl2 = [318.36,384-180.55] 
Pr2 = [223.26,384-178.93] 
Pl3 = [247.01,384-228.00] 
Pr3 = [147.036,384-228.629]
#Pl4 = [268.1624283,384-196.9579168]
#Pr4 = [380.9819863,384-197.3868557]
Pl5 = [122.4970724,384-255.5938338]
Pr5 = [254.4025837,384-258.4559182]
#Pl6 = [101.9839782,384-328.4487622]
#Pr6 = [157.0699359,384-328.4861723]
#Pl7 = [117.1437091,384-372.7670914]
#Pr7 = [154.1756298,384-372.2922456]
Pl8 = [69.04573449,384-327.5660105]
Pr8 = [200.9878585,384-327.1738984]
Pl9 = [159.2819549,384-306.8727401]
Pr9 = [277.7101701,384-313.5317582]
#Pl10 = [246.184615,66.758974]
#Pr10 = [198.102990,60.109635]
#Pl11 = [255.875587,67.098592]
#Pr11 = [210.071705,60.023256]
Pl12 = [296.0, 185.0]
Pr12 = [99.0, 186]
#Pl13 = [251.991004,49.052474]
#Pr13 = [203.005249,41.871391]
Pl14 = [245.082456,17.017544]
Pr14 = [234.976577,5.996396]
Pl15 = [345,262]
Pr15 = [67,267]
#Pl16 = [345,253]
#Pr16 = [73,257]
#Pl17 = [342,239]
#Pr17 = [81,243]
#Pl18 = [335,223]
#Pr18 = [88,226]
#'''

(384, 384)


In [2]:
#'''
PL = []
PL.append(Pl0)
PL.append(Pl1)
PL.append(Pl2)
PL.append(Pl3)
#PL.append(Pl4)
PL.append(Pl5)
#PL.append(Pl6)
#PL.append(Pl7)
PL.append(Pl8)
PL.append(Pl9)
#PL.append(Pl10)
#PL.append(Pl11)
PL.append(Pl12)
#PL.append(Pl13)
PL.append(Pl14)
PL.append(Pl15)
#PL.append(Pl16)
#PL.append(Pl17)
#PL.append(Pl18)
PR = []
PR.append(Pr0)
PR.append(Pr1)
PR.append(Pr2)
PR.append(Pr3)
#PR.append(Pr4)
PR.append(Pr5)
#PR.append(Pr6)
#PR.append(Pr7)
PR.append(Pr8)
PR.append(Pr9)
#PR.append(Pr10)
#PR.append(Pr11)
PR.append(Pr12)
#PR.append(Pr13)
PR.append(Pr14)
PR.append(Pr15)
#PR.append(Pr16)
#PR.append(Pr17)
#PR.append(Pr18)
#'''

In [3]:
A = []
one = [1,1,1,1,1,1,1,1,1]
zero = [0,0,0,0,0,0,0,0,0]
#for ip in range(len(calPoint)):
    #plx = calPoint['XL'].iloc[ip]
    #ply = calPoint['YL'].iloc[ip]
    #prx = calPoint['XR'].iloc[ip]
    #pry = calPoint['YR'].iloc[ip]
    #print(plx,ply,prx,pry)
for ip in range(len(PL)):
    plx = PL[ip][0]
    ply = PL[ip][1]
    prx = PR[ip][0]
    pry = PR[ip][1]
    xlxr = plx*prx
    xlyr = plx*pry
    xl = plx
    ylxr = ply*prx
    ylyr = ply*pry
    yl = ply
    xr = prx
    yr = pry
    null = 1
    Ai = [xlxr,xlyr,xl,ylxr,ylyr,yl,xr,yr,1]
    A.append(Ai) 
Aarray = np.matrix(A)
AarrayT = Aarray.transpose()
AA = Aarray.transpose()*Aarray
AA

matrix([[  1.48167604e+10,   1.19426018e+10,   8.11375314e+07,
           7.78975872e+09,   8.04478590e+09,   4.58608716e+07,
           6.50694198e+07,   4.50578710e+07,   3.39832864e+05],
        [  1.19426018e+10,   1.96282719e+10,   9.54511831e+07,
           8.04478590e+09,   1.38993156e+10,   6.66616870e+07,
           4.50578710e+07,   6.70877848e+07,   3.46022592e+05],
        [  8.11375314e+07,   9.54511831e+07,   5.57096216e+05,
           4.58608716e+07,   6.66616870e+07,   3.47993435e+05,
           3.39832864e+05,   3.46022592e+05,   2.20725122e+03],
        [  7.78975872e+09,   8.04478590e+09,   4.58608716e+07,
           5.21610746e+09,   5.59004865e+09,   3.12042924e+07,
           3.60319456e+07,   3.10764932e+07,   1.98320933e+05],
        [  8.04478590e+09,   1.38993156e+10,   6.66616870e+07,
           5.59004865e+09,   1.00105074e+10,   4.77142003e+07,
           3.10764932e+07,   4.80448508e+07,   2.45450581e+05],
        [  4.58608716e+07,   6.66616870e+07,   3.4

In [4]:
w, v = LA.eig(AA)
v1 = v.transpose()
print(w)
print(v1)
imin = np.argmin(w)
print(imin)
en = w[imin]
ev = v1[imin]
ev

[  4.24863474e+10   6.41303315e+09   6.81758911e+08   9.18368047e+07
   4.16772134e+04   1.33936275e+04   6.35708927e+02   6.01023857e+00
   2.75269156e-03]
[[  5.06458081e-01   6.56339381e-01   3.50680380e-03   3.16661686e-01
    4.60886935e-01   2.32672691e-03   2.07745979e-03   2.32637124e-03
    1.35375875e-05]
 [  7.71893917e-01  -4.46891924e-01   9.15101554e-04   2.44904176e-01
   -3.80091069e-01  -7.61539089e-04   4.22648268e-03  -9.12364554e-04
    9.81797339e-06]
 [ -3.78351356e-01  -1.38109097e-01  -4.40101200e-03   9.15138049e-01
   -1.63204343e-02   1.78842221e-03   2.38362958e-03   1.96827815e-03
    1.64217769e-06]
 [  6.70451426e-02  -5.91933133e-01   2.38222799e-03  -4.73468577e-02
    8.01711588e-01   4.31084781e-03   9.85959378e-03   3.93011225e-03
    5.86449859e-05]
 [ -5.13707380e-03   4.45640988e-03   5.43397248e-01  -2.22796170e-03
   -9.94064018e-03   3.66171606e-01   6.68658501e-01   3.51217693e-01
    5.44962131e-03]
 [ -9.55351354e-04   4.93580452e-03  -4.653

matrix([[ -1.37575164e-06,   1.67391404e-05,  -2.56984893e-03,
           1.96866544e-05,   3.72992394e-06,   4.26309951e-02,
          -3.50318198e-03,  -4.92838682e-02,   9.97865132e-01]])

In [5]:
AA*ev.transpose()

matrix([[ -3.25962901e-09],
        [  5.35510480e-08],
        [ -7.07392246e-06],
        [  5.56465238e-08],
        [  1.44354999e-08],
        [  1.17350004e-04],
        [ -9.64315041e-06],
        [ -1.35663264e-04],
        [  2.74681493e-03]])

In [6]:
ev1 = np.array(ev)
ev1 = ev1[0]
F = [[ev1[0],ev1[3],ev1[6]],[ev1[1],ev1[4],ev1[7]],[ev1[2],ev1[5],ev1[8]]]
MatrixL = np.array(F)
MatrixR = MatrixL.transpose()
MatrixL

array([[ -1.37575164e-06,   1.96866544e-05,  -3.50318198e-03],
       [  1.67391404e-05,   3.72992394e-06,  -4.92838682e-02],
       [ -2.56984893e-03,   4.26309951e-02,   9.97865132e-01]])

In [9]:
bk0L = imread('./Data/Shot{}/Clean_Data_Shot{}_Cam_{}/FrameL0.tif'.format(shot,shot,picL))
bk0R = imread('./Data/Shot{}/Clean_Data_Shot{}_Cam_{}/FrameR0.tif'.format(shot,shot,picR))
plt.figure(figsize=[3,3])
plt.imshow(bk0L)
x = np.arange(0,width,1)
'''
for ip in range(0,len(calPoint)):
    plx = calPoint['XL'].iloc[ip]
    ply = calPoint['YL'].iloc[ip]
    prx = calPoint['XR'].iloc[ip]
    pry = calPoint['YR'].iloc[ip]
    ipL = [plx,ply,1]
    ipR = [prx,pry,1]
'''
for ip in range(len(PL)):
    plx = PL[ip][0]
    ply = PL[ip][1]
    prx = PR[ip][0]
    pry = PR[ip][1]
    ipL = PL[ip]
    ipR = PR[ip]
    off = np.ones((1,1))
    ipL = np.append(ipL, off)
    ipR = np.append(ipR, off)
    LineL = np.dot(ipR,MatrixL) #points in the right frame and the corresponding epipolar lines in the left frame
    LineR = np.dot(ipL,MatrixR) #points in the left frame and the corresponding epipolar lines in the right frame
    yL = (-LineL[2]-LineL[0]*x)/LineL[1]
    yR = (-LineR[2]-LineR[0]*x)/LineR[1]
    dlr = math.fabs(np.dot(ipL,LineL))/math.sqrt(LineL[0]*LineL[0]+LineL[1]*LineL[1])
    drl = math.fabs(np.dot(ipR,LineR))/math.sqrt(LineR[0]*LineR[0]+LineR[1]*LineR[1])  
    plt.plot(x,yL,color='g',linestyle=':')
    #plt.plot(x,yR,color='r')
    #plt.plot(prx,pry,"o",color='r')    
    plt.plot(plx,ply,"o",color='g') 
    plt.xlabel('X');
    plt.ylabel('Y');
    #print(ip,dlr,drl)
#plt.show()
plt.ylim(384,0)
#plt.show()
plt.subplots_adjust(bottom=0.2)
plt.savefig("./CalibrationL_10_Shot{}.pdf".format(shot))
plt.figure(figsize=[3,3])
plt.imshow(bk0R)
for ip in range(len(PR)):
    plx = PL[ip][0]
    ply = PL[ip][1]
    prx = PR[ip][0]
    pry = PR[ip][1]
    ipL = PL[ip]
    ipR = PR[ip]
    off = np.ones((1,1))
    ipL = np.append(ipL, off)
    ipR = np.append(ipR, off)
    LineL = np.dot(ipR,MatrixL) #points in the right frame and the corresponding epipolar lines in the left frame
    LineR = np.dot(ipL,MatrixR) #points in the left frame and the corresponding epipolar lines in the right frame
    yL = (-LineL[2]-LineL[0]*x)/LineL[1]
    yR = (-LineR[2]-LineR[0]*x)/LineR[1]
    dlr = math.fabs(np.dot(ipL,LineL))/math.sqrt(LineL[0]*LineL[0]+LineL[1]*LineL[1])
    drl = math.fabs(np.dot(ipR,LineR))/math.sqrt(LineR[0]*LineR[0]+LineR[1]*LineR[1])  
    #plt.plot(x,yL,color='g')
    plt.plot(x,yR,color='r',linestyle=':')
    plt.plot(prx,pry,"o",color='r')
    plt.xlabel('X');
    plt.ylabel('Y');
    #plt.plot(plx,ply,"o",color='g')  
    #print(ip,dlr,drl)
#plt.show()
plt.ylim(384,0)
#plt.show()
plt.subplots_adjust(bottom=0.2)
plt.savefig("./CalibrationR_10_Shot{}.pdf".format(shot))

In [8]:
plt.figure(figsize=[24,24])
plt.imshow(bk0R+bk0L)
plt.savefig("bk.tif")